# Generated by Django 4.2.3 on 2023-07-27 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0003_passanger"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Passanger",
            new_name="Passenger",
        ),
    ]
