# Generated by Django 4.2.4 on 2023-09-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_user_likes_delete_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="likes",
            field=models.ManyToManyField(
                null=True, related_name="user_likes", to="network.post"
            ),
        ),
    ]
