# Generated by Django 4.2.4 on 2023-10-04 12:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_alter_user_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(limit_value=0)],
            ),
        ),
    ]
