# Generated by Django 4.2.4 on 2023-10-04 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0005_alter_followers_user_alter_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followers",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
