# Generated by Django 4.2.4 on 2023-08-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_listing_current_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="listing",
            field=models.ManyToManyField(
                related_name="watchlist", to="auctions.listing"
            ),
        ),
    ]
